### ISSUE TITLE
Discord link in the community section has expired.

### ISSUE THREAD

**Issue by pvonmoradi** [mcauser/awesome-micropython#13]
Discord link in the community section has expired. 
https://discord.gg/5GjKNE

**Comment by mcauser** [comment]
Fixed in https://github.com/mcauser/awesome-micropython/commit/508e12a59ca6d1b48d3acddf463881e62ce30dd2

**Comment by pvonmoradi** [comment]
Still getting expired or lack of permission to join.  
Tested this link: [https://discord.com/invite/qw7d8bv](https://discord.com/invite/qw7d8bv)  
Isn't it better to create a Matrix server so it wouldn't be propriety?
